### ISSUE TITLE
Fix https

### ISSUE THREAD

**Issue by fedorov** [OSIPI/osipi.github.io#4]
When switching to https, site becomes broken. Likely some resources are external via http? Need to check and see if can be fixed.

**Comment by notZaki** [comment]
The `url` configured in
https://github.com/OSIPI/osipi.github.io/blob/9ca204e2ebf3bfee799f73c81547a7bafc90b519/_config.yml#L28
is used to load resources (e.g. icons, scripts).
The https version of the website will refuse to load these resources if the `url` is not using https---causing the site to appear broken with missing/incomplete elements.

The https version of the site is broken because even though the above `url` uses https, it is redirecting to **http**://www.osipi.org which is not using https.
The errors can be seen using the Chrome/Inspect console on the https version of the site.

This will probably by making `https://osipi.github.io` redirect to **https**://www.osipi.org.

I did a quick test by making a [temporary site](https://osipitest.netlify.com/) and changing the `url` to point to the temporary site (which uses https), and it seems to be working fine.

**Comment by fedorov** [comment]
Let me try this. There is a setting in the github hosting panel.

I will also invite you to the organization!

**Comment by fedorov** [comment]
@notZaki I tried changing the URL in GitHub to https, but got the below:

![image](https://user-images.githubusercontent.com/313942/57867203-aebb7580-77ce-11e9-83f5-10e76aa83224.png)

![image](https://user-images.githubusercontent.com/313942/57867225-bc70fb00-77ce-11e9-9d46-179ef9588fe6.png)

Do you know what is going on?

**Comment by notZaki** [comment]
It takes a short while for the page to update.

The page looks fine to me right now (with https!).

**Comment by fedorov** [comment]
Indeed, it works now! thank you!

So good to close this issue!

**Comment by fedorov** [comment]
So it opens fine in Incognito mode, but not otherwise. Unfortunately, I don't have time to debug this at the moment... :-(

**Comment by fedorov** [comment]
Maybe some caching issue

**Comment by notZaki** [comment]
Yea, it might be a caching issue since it looks ok to me without incognito. 
Same on Firefox/Edge/Opera/Smartphone.

**Comment by fedorov** [comment]
Following the recipe for "hard reload" (see https://superuser.com/questions/721692/google-chrome-clear-cache-for-specific-website), the site loads fine for me now!
